[package]
name = "photo-report-generator"
version = "2.1.2"
description = "照片清冊產生器"
authors = ["臺南市政府警察局"]
edition = "2021"

[lib]
name = "photo_report_generator_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
